### ISSUE TITLE
vcd org delete fails with message about system initialization failure

### ISSUE THREAD

**Issue by hodgesrm** [vmware/vcd-cli#215]
vCD CLI commands to deleted orgs fail with an internal error.  Here's an example of how to recreate. 
```
vcd org delete -r -f pyvcloud_test
Are you sure you want to delete the Org? [y/N]: y
Usage: vcd org delete [OPTIONS] <name>

Error: System initialization failed as arguments are either invalid or None
```
The root cause is a bug in instantiating the pyvcloud System class, as shown by the stack trace in vcd.log.
```
Traceback (most recent call last):
  File "/home/rhodges/git/vcd-cli/vcd_cli/org.py", line 185, in delete
    system = System(client)
  File "/home/rhodges/git/pyvcloud/pyvcloud/vcd/system.py", line 36, in __init__
    raise TypeError("System initialization failed as arguments"
TypeError: System initialization failed as arguments are either invalid or None
```

**Comment by hodgesrm** [comment]
Fixed by https://github.com/vmware/vcd-cli/pull/216.
