### ISSUE TITLE
vcd-cli login method fails

### ISSUE THREAD

**Issue by tsener** [vmware/vcd-cli#231]
This is what I get upon login;
`[root@vcd1 ~]# vcd-cli login  vcd1.pscoe.vmware.com pscoe marshall -i -w --password 123
Traceback (most recent call last):
  File "/usr/local/bin/vcd-cli", line 7, in <module>
    from vcd_cli.vcd import vcd
  File "/root/.local/lib/python3.6/site-packages/vcd_cli/vcd.py", line 110, in <module>
    load_user_plugins()
  File "/root/.local/lib/python3.6/site-packages/vcd_cli/plugin.py", line 22, in load_user_plugins
    if 'extensions' in profiles.data and \
TypeError: argument of type 'NoneType' is not iterable`

version is latest, upgraded through pip. 
Python version:2.6.6 on Cent 6.7 x64

**Comment by hodgesrm** [comment]
Hi @tsener, 

vcd-cli only works with Python 3.  Which version of vcd-cli are you using?  (`vcd version` should tell you.)

Thanks, Robert

**Comment by hodgesrm** [comment]
p.s., Also what does `python3 --version` show?

**Comment by rocknes** [comment]
From the stacktrace it looks like that profile file is corrupted or has incomplete data. Can you please upload/paste content of profiles.yaml here?

The file should be located in ~/.vcd-cli

**Comment by Laliteus** [comment]
I am facing the same issue and found ~/.vcd-cli/profiles.yaml is not located.
