### ISSUE TITLE
vcd system extension list returns no extension

### ISSUE THREAD

**Issue by fhufenreuter** [vmware/vcd-cli#234]
I try to register the cse extension

```
root@cse[ ~ ]# vcd system extension create cse cse cse vcdext '/api/cse, /api/cse/.*, /api/cse/.*/.*'
Extension registered.
root@cse [ ~ ]# vcd system extension list

root@cse [ ~ ]# vcd system extension info cse cse
Usage: vcd system extension info [OPTIONS] <name> [NAMESPACE]

Error: 'list' object is not an iterator
```
https://xxx.net/api/admin/extension/service/query returns
```xml
<QueryResultRecords xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ns9="http://www.vmware.com/vcloud/versions" name="adminService" page="1" pageSize="25" total="1" href="https://xxx.net/api/admin/extension/service/query?page=1&amp;pageSize=25&amp;format=records" type="application/vnd.vmware.vcloud.query.records+xml">
    <Link rel="alternate" href="https://xxx.net/api/admin/extension/service/query?page=1&amp;pageSize=25&amp;format=references" type="application/vnd.vmware.vcloud.query.references+xml"/>
    <Link rel="alternate" href="https://xxx.net/api/admin/extension/service/query?page=1&amp;pageSize=25&amp;format=idrecords" type="application/vnd.vmware.vcloud.query.idrecords+xml"/>
    <AdminServiceRecord enabled="true" exchange="vcdext" isAuthorizationEnabled="false" name="cse" namespace="cse" priority="0" routingKey="cse" href="https://xxx.net/api/admin/extension/service/3beeb19b-f6b4-45fa-aefb-32137d02a19f"/>
</QueryResultRecords>
```

**Comment by tsugliani** [comment]
@fhufenreuter Yes, this is definitively a bug I encountered too.
You can safely ignore the error for now and continue the setup.

/cc @pacogomez @sahithi @goelaashima

**Comment by rocknes** [comment]
Sorry, for the late reply. It looks like a pyvcloud issue,

Traceback (most recent call last):
  File "c:\code\vcd-cli\vcd_cli\extension.py", line 68, in info
    stdout(ext.get_extension_info(name, namespace), ctx)
  File "c:\code\pyvcloud\pyvcloud\vcd\api_extension.py", line 102, in get_extension_info
    ext = self.get_extension(name, namespace)
  File "c:\code\pyvcloud\pyvcloud\vcd\api_extension.py", line 72, in get_extension
    query_result_format=QueryResultFormat.ID_RECORDS).find_unique()
  File "c:\code\pyvcloud\pyvcloud\vcd\client.py", line 1397, in find_unique
    item = next(query_results)
TypeError: 'list' object is not an iterator

I will take a look and update.

**Comment by rocknes** [comment]
Issue has been fixed and being tracked by https://github.com/vmware/pyvcloud/pull/270
Please wait for next vcd-cli release to have the commands fixed.

**Comment by tsugliani** [comment]
Thanks for the fix @rocknes
