### ISSUE TITLE
Error initializing plugin EntryPoint

### ISSUE THREAD

**Issue by sebastiangrugel** [vmware/vcd-cli#235]
After fresh installation on Windows 10 every command i use similar output:

C:\Users\sebastian.grugel>vcd version
Error initializing plugin EntryPoint('windows', 'keyring.backends.Windows', None, Distribution('keyring', '13.2.1')).
Traceback (most recent call last):
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\win32ctypes\core\__init__.py", line 29, in <module>
    import cffi
ModuleNotFoundError: No module named 'cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 154, in _load_plugins
    init_func = ep.load()
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "c:\users\sebastian.grugel\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\keyring\backends\Windows.py", line 12, in <module>
    from win32ctypes.pywin32 import pywintypes
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\win32ctypes\pywin32\__init__.py", line 21, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\win32ctypes\pywin32\win32api.py", line 23, in <module>
    from win32ctypes.core import _common, _kernel32, _backend
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\win32ctypes\core\__init__.py", line 33, in <module>
    from .ctypes import _advapi32, _common, _kernel32
  File "C:\Users\sebastian.grugel\AppData\Roaming\Python\Python37\site-packages\win32ctypes\core\ctypes\_advapi32.py", line 134

    ^
SyntaxError: invalid syntax
vcd-cli, VMware vCloud Director Command Line Interface, 20.3.0

Im using Python 3.7.0

**Comment by rocknes** [comment]
We haven't tested pyvcloud and vcd-cli agains python 3.7. Can you please downgrade to python 3.6.5 and check if the issue still persists?

**Comment by sheetaltaori** [comment]
I am facing below error with python 3.6.5

~$ vcd version
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/staori/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/home/staori/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

**Comment by rocknes** [comment]
We have identified the issue to be version of keyring. Please run the following command, it should fix the issue.
` pip install 'keyring==12.0.0' --force-reinstall`

**Comment by nyetwurk** [comment]
```
$ pip3 install keyring==12.0.0 --force-reinstall
Collecting keyring==12.0.0
  Using cached https://files.pythonhosted.org/packages/bb/7a/5ae985341091b026f4c628655ad0911102a61ac758e1a0ff1cc4490b730a/keyring-12.0.0-py2.py3-none-any.whl
Collecting entrypoints (from keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/cc/8b/4eefa9b47f1910b3d2081da67726b066e379b04ca897acfe9f92bac56147/entrypoints-0.2.3-py2.py3-none-any.whl
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/d8/e8/80975fd281764c80b2eb581a7f25d2109786e273b8925e8161bd2d06d10a/SecretStorage-3.1.0-py3-none-any.whl
Collecting jeepney (from secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/2b/f7/ff23b9b59534f501d47c327576aadda59da5b83d76ff837e6075bc325b9f/jeepney-0.4-py3-none-any.whl
Collecting cryptography (from secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.4.1 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring==12.0.0)
Installing collected packages: entrypoints, jeepney, pycparser, cffi, six, idna, asn1crypto, cryptography, secretstorage, keyring
Segmentation fault (core dumped)
```

**Comment by rocknes** [comment]
@nyetwurk which platform are you on? 
If you are using venv, I would suggest to create a new venv and install pyvcloud afresh. 
Uninstall keyring and then install keyring v12.0.0 manually.

**Comment by nyetwurk** [comment]
Ubuntu
```
$ sudo -H pip3 install keyring
Requirement already satisfied: keyring in /usr/lib/python3/dist-packages
Requirement already satisfied: secretstorage in /usr/lib/python3/dist-packages (from keyring)
```

**Comment by nyetwurk** [comment]
see also https://github.com/pyca/cryptography/issues/3815

**Comment by nyetwurk** [comment]
I don't feel setting up venv's to work around these issues is a good long term solution, btw. I realize this that is a near religious position these days... but I'm old fashioned that way :) I think encouraging venvs just encourages lazy devs who don't want to worry about breaking compatibility. /offsoapbox. YMMV.

**Comment by nyetwurk** [comment]
https://github.com/pypa/pip/commit/ba80574225488e30569d787ef7e5b0b59305adeb
