### ISSUE TITLE
Time Format Error on vApp Deployment

### ISSUE THREAD

**Issue by tardoe** [vmware/vcd-cli#25]
While doing a simple vca vapp create I get a time format error. Running on OSX 10.10 running Python 2.7.6 with the latest vca-cli from pip hitting a vCloud Director Standalone instance running 5.6.4

The vApp creates but looks like it gets to just before hooking up the network before failing.

Here is the command and output:

```
Tims-Mac-mini:~ tim$ vca vapp create -a TEST-VAPP2 -c "TurnKey" -t "TURNKEY WORDPRESS" -n "Example network" -m POOL -V "Tim-Wordpress-001"
creating vApp 'TEST-VAPP2' in VDC 'DC_1119688' from template 'TURNKEY WORDPRESS' in catalog 'TurnKey'
                                                                                                                        Traceback (most recent call last):
  File "/usr/local/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==10', 'console_scripts', 'vca')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/vca_cli/vca_cli.py", line 465, in vapp
    if task: display_progress(task, ctx.obj['json_output'], vca.vcloud_session.get_vcloud_headers())
  File "/Library/Python/2.7/site-packages/vca_cli/vca_cli.py", line 1520, in display_progress
    sys.stdout.write("\r" + task_table(response.content) + '\n')
  File "/Library/Python/2.7/site-packages/vca_cli/vca_cli.py", line 1472, in task_table
    startTime = datetime.strptime(task_dict["Task"].get('@startTime'), "%Y-%m-%dT%H:%M:%S.%fZ")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2015-07-28T09:14:05.190+08:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

**Comment by hodgesrm** [comment]
Python 2.7 is no longer supported.
