### ISSUE TITLE
Cannot insert or eject media

### ISSUE THREAD

**Issue by jonasrosland** [vmware/vcd-cli#37]
I'm trying to follow the guidelines to get CoreOS working in vCA as outlined here:
http://blogs.vmware.com/vcloud/2015/02/using-coreos-vcloud-air-demand.html

When I get to the part about inserting the config ISO I get the following:

```
$ vca vapp insert --vdc VDC1 --vapp coreos1 --vm coreos_production_vmware_ova --catalog default-catalog --media coreos1-config.iso
insert media 'coreos1-config.iso', VM 'coreos_production_vmware_ova' in vApp 'coreos1' in VDC 'VDC1'
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==14', 'console_scripts', 'vca')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/vca_cli/vca_cli_compute.py", line 558, in vapp
    task = the_vapp.vm_media(vm_name, the_media, operation)
  File "/usr/local/lib/python2.7/site-packages/pyvcloud/vapp.py", line 512, in vm_media
    """ % (media.get('name'), media.get('id'), media.get('href'))
AttributeError: 'NoneType' object has no attribute 'get'
```

Some more output for troubleshooting:

```
$ vca catalog
Available catalogs and items in org 'secretorg', profile 'default':
| Catalog         | Item                                     |
|-----------------+------------------------------------------|
| Public Catalog  | CentOS64-64BIT                           |
| Public Catalog  | CentOS64-32BIT                           |
| Public Catalog  | Ubuntu Server 12.04 LTS (amd64 20150127) |
| Public Catalog  | Ubuntu Server 12.04 LTS (i386 20150127)  |
| Public Catalog  | W2K12-STD-64BIT                          |
| Public Catalog  | CentOS63-64BIT                           |
| Public Catalog  | W2K12-STD-R2-64BIT                       |
| Public Catalog  | W2K8-STD-R2-64BIT                        |
| Public Catalog  | CentOS63-32BIT                           |
| default-catalog | coreos_template                          |
| default-catalog | coreos-config1.iso                       |
```

```
$ vca vapp
Available vApps in 'VDC1', profile 'default':
| vApp    | VMs                          | Status     | Deployed   |   Description |
|---------+------------------------------+------------+------------+---------------|
| coreos1 | coreos_production_vmware_ova | Powered on | yes        |               |
```

Inserting the ISO through the web interface works as expected.

**Comment by hodgesrm** [comment]
Obsolete code.
