### ISSUE TITLE
vca vdc use --vdc command failed for account with 'End User' role

### ISSUE THREAD

**Issue by abelyaevskiy** [vmware/vcd-cli#40]
Hi!

When I login under account with _End User_ role I'm not able neither by default get vDC nor select it manually with python error `IndexError: list index out of range`. Please find log below:

``` python
~$ vca vdc use --vdc M267276419-3903
Using vdc 'M267276419-3903', profile 'default'
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==14', 'console_scripts', 'vca')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli_compute.py", line 63, in vdc
    cmd_proc.select_default_gateway()
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/cmd_proc.py", line 557, in select_default_gateway
    gateways = self.vca.get_gateways(self.vdc_name)
  File "/usr/local/lib/python2.7/dist-packages/pyvcloud/vcloudair.py", line 1214, in get_gateways
    self.response = Http.get(link[0].get_href(), headers=self.vcloud_session.get_vcloud_headers(), verify=self.verify, logger=self.logger)
IndexError: list index out of range
~$ vca vdc
Available Virtual Data Centers in org 'm267276419-3903', profile 'default':
| Virtual Data Center   | Selected   |
|-----------------------+------------|
| M267276419-3903       |            |
~$
```

When I login under account with admin role I have selected vDC by default and also I can select vDC manually.

**Comment by hodgesrm** [comment]
Obsolete code.
