### ISSUE TITLE
vca gateway del-ip

### ISSUE THREAD

**Issue by soniah** [vmware/vcd-cli#42]
deallocating public IP '' from gateway 'gateway' in VDC 'VDC1'
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==14', 'console_scripts', 'vca')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli_network.py", line 109, in gateway
    error.get_message(), cmd_proc)
  File "/usr/local/lib/python2.7/dist-packages/vca_cli/vca_cli_utils.py", line 52, in print_error
    json_message = json.loads(cmd_proc.vca.response.content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by soniah** [comment]
**vca gateway del-ip** gives the above error.

Sorry for terseness, I submitted this via hub.

**Comment by hodgesrm** [comment]
Obsolete code.
