### ISSUE TITLE
vcd vapp network services static-route enable-service fails for Tenant Org Admin

### ISSUE THREAD

**Issue by IAmAnthem** [vmware/vcd-cli#518]
As a tenant, I don't have full access to my vCloud Director environment.
I found this module and was excited!
But when I use the command, it seems like I potentially am not getting back the HREF you're looking for, because of my limited access?
There must be some difference between me and whatever user level the unit tests run at?

***vcd_cli_error.log***
```
Traceback (most recent call last):
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/vcd_cli/vapp_network_static_route.py", line 89, in enable_service
    network_name)
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/vcd_cli/vapp_network_static_route.py", line 72, in get_vapp_network_static_route
    vapp_static_route = VappStaticRoute(client, vapp_name, network_name)
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp_services.py", line 48, in __init__
    self._build_self_href()
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp_services.py", line 63, in _build_self_href
    self.parent = self._get_parent_by_name()
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp_services.py", line 101, in _get_parent_by_name
    records = list(query.execute())
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1829, in execute
    raise OperationNotSupportedException('Unable to execute query.')
pyvcloud.vcd.exceptions.OperationNotSupportedException: Unable to execute query.

Traceback (most recent call last):
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/vcd_cli/vapp_network_static_route.py", line 134, in list
    network_name)
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/vcd_cli/vapp_network_static_route.py", line 72, in get_vapp_network_static_route
    vapp_static_route = VappStaticRoute(client, vapp_name, network_name)
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp_services.py", line 48, in __init__
    self._build_self_href()
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp_services.py", line 63, in _build_self_href
    self.parent = self._get_parent_by_name()
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp_services.py", line 101, in _get_parent_by_name
    records = list(query.execute())
  File "/home/MYACCOUNT/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1829, in execute
    raise OperationNotSupportedException('Unable to execute query.')
pyvcloud.vcd.exceptions.OperationNotSupportedException: Unable to execute query.
```

I also have the vcd.log for this, but its a bit spammy.

**Comment by IAmAnthem** [comment]
Closing, converted infrastructure to terraform
