### ISSUE TITLE
ModuleNotFoundError on FreeBSD (pysqlite2)

### ISSUE THREAD

**Issue by rohankrishnadev** [vmware/vcd-cli#522]
I'm running into issues with vcd-cli installed on FreeBSD. ```vcd``` seems to require a Python 2 module (pysqlite2). 

```bash
[~] vcd --help
Traceback (most recent call last):
  File "/home/rohan/.local/lib/python3.7/site-packages/vcd_cli/browsercookie/__init__.py", line 18, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/.local/bin/vcd", line 6, in <module>
    from vcd_cli.vcd import vcd
  File "/home/rohan/.local/lib/python3.7/site-packages/vcd_cli/vcd.py", line 121, in <module>
    from vcd_cli import login  # NOQA
  File "/home/rohan/.local/lib/python3.7/site-packages/vcd_cli/login.py", line 24, in <module>
    from vcd_cli import browsercookie
  File "/home/rohan/.local/lib/python3.7/site-packages/vcd_cli/browsercookie/__init__.py", line 20, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```
The required module does not seem to be supported by Python 3.
```bash
[~] pip search pysqlite2
[~] pip search pysqlite3
sqlalchemy-pysqlite3 (0.0.4)  - SQLAlchemy dialect to use pysqlite3 dbapi2
pysqlite3 (0.4.2)             - DB-API 2.0 interface for Sqlite 3.x
pysqlite3-binary (0.4.2)      - DB-API 2.0 interface for Sqlite 3.x
```

Additional details:
```
[~] python --version
Python 3.7.6
[~] pip --version
pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
[~] freebsd-version
11.3-RELEASE-p7
```

**Comment by vmguru007** [comment]
Hi,

I am having exactly the same issue on CentOS 8.2 where vCD CLI is installed by CSE 2.6.1. Did you get to resolve this?
